name: CI/CD Workflow

on:
  push:
    branches:
      - prod
      - uat
      - dev

jobs:
  approve:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - name: Approval Required
        run: echo "Approval is required to proceed with this workflow."
